# Generated by Django 5.0.4 on 2024-04-23 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='language_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='English_Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=256)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category_list')),
            ],
        ),
        migrations.CreateModel(
            name='URL_dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDN_domain', models.TextField()),
                ('ssl_configuration_status', models.BooleanField(default=True)),
                ('idn_domain_running_status', models.BooleanField(default=True)),
                ('content_language', models.TextField()),
                ('updated_On', models.DateField(auto_now_add=True)),
                ('Last_Updated_On', models.DateField(auto_now=True)),
                ('Remark', models.TextField()),
                ('English_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.english_domain')),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language_list')),
            ],
        ),
    ]
