# Generated by Django 5.0.4 on 2024-04-23 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_list',
            options={'verbose_name_plural': 'category_list'},
        ),
        migrations.AlterModelOptions(
            name='english_domain',
            options={'verbose_name_plural': 'English_Domain'},
        ),
        migrations.AlterModelOptions(
            name='language_list',
            options={'verbose_name_plural': 'language_list'},
        ),
        migrations.AlterModelOptions(
            name='url_dashboard',
            options={'verbose_name_plural': 'URL_dashboard'},
        ),
        migrations.AddField(
            model_name='category_list',
            name='Last_Updated_On',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='category_list',
            name='updated_On',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='english_domain',
            name='Last_Updated_On',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='english_domain',
            name='updated_On',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='language_list',
            name='Last_Updated_On',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='language_list',
            name='updated_On',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='url_dashboard',
            name='idn_domain_running_status',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='url_dashboard',
            name='ssl_configuration_status',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='url_dashboard',
            name='updated_On',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
